export const defaultImages = {
  USER: '/assets/user.jpg',
};

export const defaultName = {
  USER: 'Username',
};

export const validateMessage = {
  REQUIRED_EXIST: 'Must not be empty',
};

export const actionTypes = {
  auth: {
    GET_AUTH_USER: 'GET_AUTH_USER',
    LOGIN: 'LOGIN',
    REGISTER: 'REGISTER',
  },
  post: {
    GET_POSTS: 'GET_POSTS',
    GET_POST: 'GET_POST',
    CREATE_POST: 'CREATE_POST',
    LIKE_POST: 'LIKE_POST',
    UNLIKE_POST: 'UNLIKE_POST',
    DELETE_POST: 'DELETE_POST',
    COMMENT_ON_POST: 'COMMENT_ON_POST',
    DELETE_COMMENT: 'DELETE_COMMENT',
  },
  profile: {
    UPLOAD_PROFILE_IMAGE: 'UPLOAD_PROFILE_IMAGE',
    GET_PROFILES: 'GET_PROFILES',
    GET_PROFILE: 'GET_PROFILE',
    GET_GITHUB_REPOSITORIES: 'GET_GITHUB_REPOSITORIES',
    PROFILE_ACTIONS: 'PROFILE_ACTIONS',
    ADD_EXPERIENCE: 'ADD_EXPERIENCE',
    ADD_EDUCATION: 'ADD_EDUCATION',
    DELETE_EXPERIENCE: 'DELETE_EXPERIENCE',
    DELETE_EDUCATION: 'DELETE_EDUCATION',
    DELETE_ACCOUNT: 'DELETE_ACCOUNT',
  },
};
